### ISSUE TITLE
DO NOT REPLY!!!

### ISSUE THREAD

**Issue by ghost** [PolyMarsDev/Minecraft-Skin-Grabber#5]
How do i download this file. (I'M NOT BUILDING IT FROM SOURCE IN UNITY.)

**Comment by hdfsyu** [comment]
you have to

**Comment by hdfsyu** [comment]
then again you cant because the api has died

**Comment by hdfsyu** [comment]
never mind it got replaced with a new one

**Comment by ghost** [comment]
@hdfsyu All of your answers are not correct, AS I SAID I WON'T BUILD IT from scratch

**Comment by hdfsyu** [comment]
> @hdfsyu All of your answers are not correct, AS I SAID I WON'T BUILD IT from scratch

theres nothing in releases, also whats the problem from bulding it from scratch!? you also need to look in the code and replace the api token with your own
